packages:
  - .

allowBuilds:
  core-js: false
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - stripe@22.3.2

overrides:
  '@better-auth/passkey': 1.6.13
  better-auth: 1.6.13
  postcss: 8.5.15

patchedDependencies:
  '@neondatabase/auth-ui@0.2.1-beta': patches/@neondatabase__auth-ui@0.2.1-beta.patch
  '@neondatabase/auth@0.4.2-beta': patches/@neondatabase__auth@0.4.2-beta.patch
