import { sql } from "drizzle-orm";
import { boolean, check, index, integer, jsonb, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid, type AnyPgColumn } from "drizzle-orm/pg-core";

export const matchStatus = pgEnum("match_status", ["pending", "active", "complete", "abandoned"]);
export const memberRole = pgEnum("room_member_role", ["owner", "player", "spectator"]);
export const subscriptionStatus = pgEnum("subscription_status", ["trialing", "active", "past_due", "canceled", "unpaid", "incomplete"]);

export const users = pgTable("users", { id: uuid("id").primaryKey().defaultRandom(), authSubject: text("auth_subject").notNull(), email: text("email").notNull(), stripeCustomerId: text("stripe_customer_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("users_auth_subject_uq").on(t.authSubject), uniqueIndex("users_email_uq").on(t.email), uniqueIndex("users_stripe_customer_uq").on(t.stripeCustomerId), check("users_email_normalized", sql`${t.email} = lower(${t.email})`)]);
export const profiles = pgTable("profiles", { userId: uuid("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), displayName: text("display_name").notNull(), avatarUrl: text("avatar_url"), preferences: jsonb("preferences").notNull().default({}), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const rooms = pgTable("rooms", { id: uuid("id").primaryKey().defaultRandom(), code: text("code").notNull(), ownerUserId: uuid("owner_user_id").notNull().references(() => users.id, { onDelete: "restrict" }), settings: jsonb("settings").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), expiresAt: timestamp("expires_at", { withTimezone: true }) }, (t) => [uniqueIndex("rooms_code_uq").on(t.code), index("rooms_owner_idx").on(t.ownerUserId)]);
export const roomMembers = pgTable("room_members", { roomId: uuid("room_id").notNull().references(() => rooms.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), role: memberRole("role").notNull(), joinedAt: timestamp("joined_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [primaryKey({ columns: [t.roomId, t.userId] }), index("room_members_user_idx").on(t.userId)]);
export const matches = pgTable("matches", { id: uuid("id").primaryKey().defaultRandom(), roomId: uuid("room_id").references(() => rooms.id, { onDelete: "set null" }), mode: text("mode").notNull(), status: matchStatus("status").notNull().default("pending"), options: jsonb("options").notNull(), stateVersion: integer("state_version").notNull().default(0), winnerPlayerId: uuid("winner_player_id").references((): AnyPgColumn => players.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp("completed_at", { withTimezone: true }) }, (t) => [index("matches_room_idx").on(t.roomId), index("matches_status_idx").on(t.status), check("matches_state_version_nonnegative", sql`${t.stateVersion} >= 0`)]);
export const players = pgTable("players", { id: uuid("id").primaryKey().defaultRandom(), matchId: uuid("match_id").notNull().references(() => matches.id, { onDelete: "cascade" }), userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }), seat: integer("seat").notNull(), displayName: text("display_name").notNull(), isBot: boolean("is_bot").notNull().default(false), botLevel: integer("bot_level") }, (t) => [uniqueIndex("players_match_seat_uq").on(t.matchId, t.seat), index("players_user_idx").on(t.userId), check("players_seat_nonnegative", sql`${t.seat} >= 0`), check("players_bot_level_range", sql`${t.botLevel} is null or (${t.botLevel} between 1 and 20)`)]);
// `legNumber` is the visit's grouping unit: the leg in X01, and 1 throughout in the
// modes that have no legs — their round is recoverable from turn order and seat count.
// `dartsThrown` and `aggregateScore` are what make a row lossless: a visit typed as a
// total leaves no darts behind, and if it busted, the score it claimed is otherwise gone.
export const turns = pgTable("turns", { id: uuid("id").primaryKey().defaultRandom(), matchId: uuid("match_id").notNull().references(() => matches.id, { onDelete: "cascade" }), playerId: uuid("player_id").notNull().references(() => players.id, { onDelete: "cascade" }), turnNumber: integer("turn_number").notNull(), legNumber: integer("leg_number").notNull().default(1), scoreBefore: integer("score_before").notNull(), scoreAfter: integer("score_after").notNull(), bust: boolean("bust").notNull().default(false), dartsThrown: integer("darts_thrown").notNull(), aggregateScore: integer("aggregate_score"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("turns_match_number_uq").on(t.matchId, t.turnNumber), index("turns_player_idx").on(t.playerId), check("turns_leg_number_positive", sql`${t.legNumber} >= 1`), check("turns_darts_thrown_range", sql`${t.dartsThrown} between 1 and 3`), check("turns_aggregate_score_range", sql`${t.aggregateScore} is null or ${t.aggregateScore} between 0 and 180`)]);
export const darts = pgTable("darts", { id: uuid("id").primaryKey().defaultRandom(), turnId: uuid("turn_id").notNull().references(() => turns.id, { onDelete: "cascade" }), ordinal: integer("ordinal").notNull(), segment: integer("segment").notNull(), multiplier: integer("multiplier").notNull(), x: integer("x_microunits"), y: integer("y_microunits") }, (t) => [uniqueIndex("darts_turn_ordinal_uq").on(t.turnId, t.ordinal), check("darts_ordinal_range", sql`${t.ordinal} between 1 and 3`), check("darts_segment_legal", sql`${t.segment} = 0 or ${t.segment} between 1 and 20 or ${t.segment} = 25`), check("darts_segment_multiplier_legal", sql`(${t.segment} = 0 and ${t.multiplier} = 1) or (${t.segment} between 1 and 20 and ${t.multiplier} between 1 and 3) or (${t.segment} = 25 and ${t.multiplier} between 1 and 2)`)]);
export const subscriptions = pgTable("subscriptions", { userId: uuid("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), stripeCustomerId: text("stripe_customer_id").notNull(), stripeSubscriptionId: text("stripe_subscription_id"), stripeSubscriptionCreatedAt: timestamp("stripe_subscription_created_at", { withTimezone: true }), plan: text("plan").notNull().default("free"), status: subscriptionStatus("status").notNull(), currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }), cancelAt: timestamp("cancel_at", { withTimezone: true }), cancelAtPeriodEnd: boolean("cancel_at_period_end").notNull().default(false), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("subscriptions_customer_uq").on(t.stripeCustomerId), uniqueIndex("subscriptions_stripe_subscription_uq").on(t.stripeSubscriptionId)]);
export const webhookEvents = pgTable("webhook_events", { stripeEventId: text("stripe_event_id").primaryKey(), type: text("type").notNull(), payload: jsonb("payload").notNull(), processingStartedAt: timestamp("processing_started_at", { withTimezone: true }), processedAt: timestamp("processed_at", { withTimezone: true }) }, (t) => [index("webhook_events_processed_idx").on(t.processedAt)]);
