"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Button, CommandDock, IconButton, Modal, Surface, Tabs, TextField } from "navi-ui";
import { applyDart, BOARD_CLOCKWISE, BOARD_RADII, checkoutAdvice, chooseAiAim, createX01, dart, notation, representativePoint, scoreBoardPoint, seededRandom, throwAiDart, undoLastDart, type Dart, type InRule, type OutRule, type X01State } from "@/domain";
import { VoiceControl } from "./voice-control";

const SEGMENTS = BOARD_CLOCKWISE;
const BOARD_CENTER=160,BOARD_RADIUS=136;
const R={innerBull:BOARD_RADII.innerBull*BOARD_RADIUS,outerBull:BOARD_RADII.outerBull*BOARD_RADIUS,trebleInner:BOARD_RADII.trebleInner*BOARD_RADIUS,trebleOuter:BOARD_RADII.trebleOuter*BOARD_RADIUS,doubleInner:BOARD_RADII.doubleInner*BOARD_RADIUS,outer:BOARD_RADII.outer*BOARD_RADIUS};
function polar(radius:number,degrees:number){const angle=degrees*Math.PI/180,round=(value:number)=>Math.round(value*10_000)/10_000;return{x:round(BOARD_CENTER+radius*Math.cos(angle)),y:round(BOARD_CENTER+radius*Math.sin(angle))}}
function ringPath(inner:number,outer:number,start:number,end:number){const a=polar(outer,start),b=polar(outer,end),c=polar(inner,end),d=polar(inner,start);return `M${a.x} ${a.y} A${outer} ${outer} 0 0 1 ${b.x} ${b.y} L${c.x} ${c.y} A${inner} ${inner} 0 0 0 ${d.x} ${d.y} Z`;}
function positioned(value:Dart):Dart{return value.x!==undefined&&value.y!==undefined?value:dart(value.segment,value.multiplier,representativePoint(value))}
const ALL_SCORES = [dart(20,3),dart(19,3),dart(18,3),dart(17,3),dart(16,3),dart(15,3),dart(14,3),dart(13,3),dart(12,3),dart(11,3),dart(10,3),...Array.from({length:20},(_,i)=>dart((20-i) as Dart["segment"],2)),dart(25,2),...Array.from({length:20},(_,i)=>dart((20-i) as Dart["segment"],1)),dart(25,1),dart(0)];
function dartsForScore(total:number): Dart[] | null { for(const a of ALL_SCORES)for(const b of ALL_SCORES)for(const c of ALL_SCORES)if(a.score+b.score+c.score===total)return[a,b,c];return null; }
function runAiTurn(state:X01State,level:number):X01State { let next=state;const rng=seededRandom(state.turns.length*101+level);while(next.status==="playing"&&next.currentPlayer===1){const aim=chooseAiAim(next.scores[1]??501);next=applyDart(next,throwAiDart(level,aim,rng).dart);}return next; }

export function X01Match() {
  const params=useSearchParams();
  const requestedStart=Number(params.get("start")),requestedLevel=Number(params.get("level")),requestedBest=Number(params.get("best"));
  const start=[301,501,701,1001].includes(requestedStart)?requestedStart:501,level=Number.isInteger(requestedLevel)?Math.min(20,Math.max(1,requestedLevel)):8,bestOf=[1,3,5,7].includes(requestedBest)?requestedBest:5;
  const inParam=params.get("in"),outParam=params.get("out"),inRule:InRule=inParam==="double"||inParam==="master"?inParam:"straight",outRule:OutRule=outParam==="straight"||outParam==="master"?outParam:"double",isAi=params.get("opponent")!=="local";
  const [game,setGame]=useState(()=>createX01({startingScore:start,legsToWin:Math.ceil(bestOf/2),setsToWin:1,inRule,outRule},[{id:"you",name:"Player 1"},{id:"ai",name:isAi?"The Navigator":"Player 2"}]));
  const aiTimer=useRef<number|null>(null),aiGeneration=useRef(0);
  const [scoreInput,setScoreInput]=useState(""), [inputMode,setInputMode]=useState("board"), [correction,setCorrection]=useState(false), [message,setMessage]=useState("Your throw · 3 darts");
  const you=game.scores[0]??start,ai=game.scores[1]??start,darts=game.currentDarts,checkoutScore=game.scores[game.currentPlayer]??start;
  const checkout=useMemo(()=>checkoutAdvice(checkoutScore,Math.max(1,3-darts.length) as 1|2|3,outRule),[checkoutScore,darts.length,outRule]);
  const averages=useMemo(()=>["you","ai"].map(id=>{const turns=game.turns.filter(t=>t.playerId===id&&!t.bust);return turns.length?(turns.reduce((n,t)=>n+t.scoreBefore-t.scoreAfter,0)/turns.length).toFixed(2):null;}),[game.turns]);
  useEffect(()=>()=>{aiGeneration.current+=1;if(aiTimer.current!==null)window.clearTimeout(aiTimer.current)},[]);

  function cancelAi(){aiGeneration.current+=1;if(aiTimer.current!==null){window.clearTimeout(aiTimer.current);aiTimer.current=null}}
  function commit(next:X01State){setGame(next);if(next.status==="complete"){cancelAi();setMessage(`${next.players.find(p=>p.id===next.winnerId)?.name} wins the match`);return;}if(next.currentPlayer===1&&isAi){cancelAi();const generation=aiGeneration.current;setMessage("AI is at the oche…");aiTimer.current=window.setTimeout(()=>{if(generation!==aiGeneration.current)return;setGame(runAiTurn(next,level));aiTimer.current=null;setMessage("Your throw · 3 darts");},450);}else setMessage(`${next.players[next.currentPlayer]?.name} · ${3-next.currentDarts.length} darts`);}
  function addDart(value:Dart){if((isAi&&game.currentPlayer!==0)||game.status==="complete")return;const placed=positioned(value);commit(applyDart(game,placed));setMessage(`${notation(placed)} registered`);}
  function submitTurn(raw?:number){if(raw===undefined){let next=game;const player=next.currentPlayer;while(next.status==="playing"&&next.currentPlayer===player&&next.currentDarts.length<3)next=applyDart(next,positioned(dart(0)));commit(next);return;}if(raw<0||raw>180){setMessage("Enter a score from 0 to 180");return;}const finish=raw===game.scores[game.currentPlayer]?checkoutAdvice(raw,3,outRule).primary:null;const values=finish??dartsForScore(raw);if(!values){setMessage("That score cannot be made with three darts");return;}let next=game;const player=next.currentPlayer;for(const value of values){if(next.status!=="playing"||next.currentPlayer!==player)break;next=applyDart(next,positioned(value));}while(next.status==="playing"&&next.currentPlayer===player&&next.currentDarts.length<3)next=applyDart(next,positioned(dart(0)));setScoreInput("");commit(next);}
  function undo(){cancelAi();setGame(current=>{let previous=undoLastDart(current);if(isAi&&current.currentPlayer===0&&current.currentDarts.length===0&&current.turns.at(-1)?.playerId==="ai")while(previous.currentPlayer===1&&previous.past.length)previous=undoLastDart(previous);return previous;});setMessage("Your latest dart is ready to correct");}
  function boardClick(e:React.MouseEvent<SVGSVGElement>){const rect=e.currentTarget.getBoundingClientRect();const x=(e.clientX-rect.left)*320/rect.width,y=(e.clientY-rect.top)*320/rect.height;addDart(scoreBoardPoint({x:(x-BOARD_CENTER)/BOARD_RADIUS,y:(y-BOARD_CENTER)/BOARD_RADIUS}));}
  return <div className="match-page">
    <header className="match-header"><div><span className="match-live"><i /> LEG 1 · LIVE</span><b>{start} / best of {bestOf}</b></div><div className="match-tools"><span>{isAi?`AI level ${level}`:"Local match"}</span><IconButton label="Correct last dart" onClick={()=>setCorrection(true)}>✎</IconButton><IconButton label="Undo last dart" onClick={undo} disabled={!game.past.length}>↶</IconButton></div></header>
    <section className="score-race" aria-label="Scoreboard"><div className={`score-player ${game.currentPlayer===0?"active":""}`}><span>You <i>{game.currentPlayer===0?"at the oche":"waiting"}</i></span><strong>{you}</strong><small>{averages[0]?`${averages[0]} avg`:"No visits yet"}</small></div><div className="leg-score"><span>LEGS</span><b>{game.legs[0]} — {game.legs[1]}</b></div><div className={`score-player ai ${game.currentPlayer===1?"active":""}`}><span>The Navigator <i>LV {level}</i></span><strong>{ai}</strong><small>{averages[1]?`${averages[1]} avg`:"No visits yet"}</small></div></section>
    <div className="match-grid">
      <section className="board-zone"><div className="board-wrap"><svg className="dartboard" viewBox="0 0 320 320" preserveAspectRatio="xMidYMid meet" role="button" tabIndex={0} aria-label="Dartboard. Click a landing point to record a dart. Press Enter to record treble twenty." onClick={boardClick} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();addDart(dart(20,3));}}}>
        <circle cx={BOARD_CENTER} cy={BOARD_CENTER} r="151" className="board-shadow"/>
        {SEGMENTS.map((number,index)=>{const center=index*18-90,start=center-9,end=center+9;const label=polar(145,center);const bed=index%2===0?"bed-dark":"bed-light";const color=index%2===0?"ring-red":"ring-green";return <g key={number} data-segment={number}><path d={ringPath(R.outerBull,R.trebleInner,start,end)} className={`board-bed ${bed}`}/><path d={ringPath(R.trebleInner,R.trebleOuter,start,end)} className={`board-bed ${color}`}/><path d={ringPath(R.trebleOuter,R.doubleInner,start,end)} className={`board-bed ${bed}`}/><path d={ringPath(R.doubleInner,R.outer,start,end)} className={`board-bed ${color}`}/><text x={label.x} y={label.y} className="board-number">{number}</text></g>})}
        <circle cx={BOARD_CENTER} cy={BOARD_CENTER} r={R.outerBull} className="outer-bull"/><circle cx={BOARD_CENTER} cy={BOARD_CENTER} r={R.innerBull} className="inner-bull"/>
        <g className="board-wires" aria-hidden="true">{[R.innerBull,R.outerBull,R.trebleInner,R.trebleOuter,R.doubleInner,R.outer].map(radius=><circle key={radius} cx={BOARD_CENTER} cy={BOARD_CENTER} r={radius}/>)}{SEGMENTS.map((number,index)=>{const point=polar(R.outer,index*18-99),inner=polar(R.outerBull,index*18-99);return <line key={number} x1={inner.x} y1={inner.y} x2={point.x} y2={point.y}/>})}</g>
        {darts.map((d,i)=>{const x=BOARD_CENTER+(d.x??0)*BOARD_RADIUS,y=BOARD_CENTER+(d.y??0)*BOARD_RADIUS;return <g key={`${notation(d)}-${i}`} className="throw-mark"><circle cx={x} cy={y} r="7"/><text x={x} y={y+3}>{i+1}</text></g>})}
      </svg><div className="board-caption"><span>Tap the landing point</span><small>or use score entry below</small></div></div></section>
      <aside className="match-side">
        <Surface className={`checkout-panel ${checkout.checkout?"checkout":checkout.bogey?"bogey":"setup"}`}><header><span>{checkout.checkout?"ON A FINISH":checkout.bogey?"BOGEY NUMBER":"SMART SETUP"}</span><b>{you}</b></header><div className="checkout-route">{(checkout.primary??checkout.setup??[]).map((value,i,route)=><span key={`${notation(value)}-${i}`}><strong>{notation(value)}</strong>{i<route.length-1&&<i>›</i>}</span>)}{checkout.leave!==null&&checkout.leave>0&&<span><strong>LEAVE {checkout.leave}</strong></span>}</div><p>{checkout.checkout?"Professional first-choice route":checkout.bogey?"No finish available — shape the next visit":"Best setup shot for a reliable leave"}</p><button type="button" disabled={!checkout.alternates.length}>Show alternate path</button></Surface>
        <Surface className="visit-panel"><Tabs label="Score input method" value={inputMode} onChange={setInputMode} items={[{label:"Board",id:"board",content:null},{label:"Turn score",id:"score",content:null},{label:"Each dart",id:"darts",content:null}]} />
          <div className="current-darts">{[0,1,2].map(i=><div key={i} className={darts[i]?"filled":""}><span>D{i+1}</span><strong>{darts[i]?notation(darts[i]!):"—"}</strong><small>{darts[i]?.score??"Waiting"}</small></div>)}</div>
          {inputMode==="score"&&<form className="score-form" onSubmit={e=>{e.preventDefault();submitTurn(Number(scoreInput));}}><TextField label="Turn score" inputMode="numeric" value={scoreInput} onChange={e=>setScoreInput(e.target.value)} placeholder="0–180"/><Button type="submit">Record visit</Button></form>}
          {inputMode==="darts"&&<div className="quick-darts">{["T20","T19","T18","D20","D16","DB","MISS"].map(label=><button key={label} onClick={()=>{if(label==="DB")addDart(dart(25,2));else if(label==="MISS")addDart(dart(0));else addDart(dart(Number(label.slice(1)) as Dart["segment"],label[0]==="T"?3:label[0]==="D"?2:1));}}>{label}</button>)}</div>}
          <Button className="end-turn" onClick={()=>submitTurn()} disabled={!darts.length}>End visit · {darts.reduce((n,d)=>n+d.score,0)}</Button>
        </Surface>
        <VoiceControl disabled={(isAi&&game.currentPlayer!==0)||game.status==="complete"} onDart={(segment,multiplier)=>addDart(dart(segment as Dart["segment"],multiplier))} onTurnScore={submitTurn} onUndo={undo} onNextPlayer={()=>submitTurn()} />
      </aside>
      <section className="history-strip"><header><h2>Visit history</h2><button onClick={undo} disabled={!game.past.length}>Undo latest</button></header>{!game.turns.length?<div className="empty-history"><span>↗</span><p>Your first visit will appear here.</p></div>:<ol>{[...game.turns].reverse().slice(0,6).map((turn,i)=><li key={`${turn.playerId}-${i}`}><span>{turn.playerId==="you"?"YOU":"AI"}</span><div>{turn.darts.map((d,j)=><b key={`${notation(d)}-${j}`}>{notation(d)}</b>)}</div><strong>{turn.scoreBefore-turn.scoreAfter}</strong><small>{turn.bust?"BUST":`${turn.scoreAfter} left`}</small></li>)}</ol>}</section>
    </div>
    <CommandDock className="match-dock"><span aria-live="polite">{message}</span><div><button onClick={undo} disabled={!game.past.length}>Undo</button><button onClick={()=>setCorrection(true)}>Correct</button><Button onClick={()=>submitTurn()} disabled={!darts.length}>End visit</Button></div></CommandDock>
    <Modal open={correction} onClose={()=>setCorrection(false)} title="Correct the latest dart"><div className="correction-body"><p>Undo the latest recorded dart, then enter it again using the board, individual darts, or turn score.</p><Button onClick={()=>{undo();setCorrection(false)}} disabled={!game.past.length}>Undo latest dart</Button><Button variant="secondary" onClick={()=>setCorrection(false)}>Keep current score</Button></div></Modal>
  </div>;
}
